// Capture only the original SRT Blob generated by the site's export action.
// No caption parsing, translation, or SRT reconstruction is performed here.
(() => {
  let armed=null, timer;
  const proto=HTMLAnchorElement.prototype;
  const oldClick=proto.click, oldDispatch=proto.dispatchEvent;
  const ownClick=Object.getOwnPropertyDescriptor(proto,'click');
  const ownDispatch=Object.getOwnPropertyDescriptor(proto,'dispatchEvent');
  function restore() {
    clearTimeout(timer); armed=null;
    if(proto.click===click) {if(ownClick) Object.defineProperty(proto,'click',ownClick); else delete proto.click;}
    if(proto.dispatchEvent===dispatch) {if(ownDispatch) Object.defineProperty(proto,'dispatchEvent',ownDispatch);else delete proto.dispatchEvent;}
  }
  function intercept(anchor) {
    if(!armed || !/\.srt$/i.test(anchor.download) || !anchor.href.startsWith('blob:')) return false;
    const nonce=armed; const filename=anchor.download, url=anchor.href; restore();
    void (async()=>{
      try {
        const blob=await (await fetch(url)).blob();
        if(blob.size>5*1024*1024) throw Error('large');
        const text=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await blob.arrayBuffer());
        window.postMessage({channel:'immersive-srt-captured',nonce,filename,text},location.origin);
      } catch {window.postMessage({channel:'immersive-srt-captured',nonce,error:true},location.origin);}
    })();
    return true;
  }
  function click(...args) {if(intercept(this)) return; return oldClick.apply(this,args);}
  function dispatch(event) {if(event.type==='click' && intercept(this)) return false; return oldDispatch.call(this,event);}
  window.addEventListener('message',e=>{
    if(e.source!==window || e.origin!==location.origin) return;
    if(e.data?.channel==='immersive-srt-disarm') {if(e.data.nonce===armed) restore();return;}
    if(e.data?.channel!=='immersive-srt-arm' || !/^[a-f0-9]{32}$/.test(e.data.nonce||'')) return;
    restore(); armed=e.data.nonce;
    proto.click=click; proto.dispatchEvent=dispatch;
    timer=setTimeout(restore,15000);
    window.postMessage({channel:'immersive-srt-armed',nonce:armed},location.origin);
  });
})();
